### ISSUE TITLE
0.7.8 release?

### ISSUE THREAD

**Issue by brakhane** [SunDwarf/curious#19]
My bot currently requires the checked out 0.7 branch because it runs into the 0.7.7 bugs.

It would be nice to have a 0.7.8 with the bugfixes to depend on.

**Comment by Fuyukai** [comment]
Oh, sure, I was planning on doing it anyway but wasn't sure if there were more changes needed. Give me a bit.

**Comment by Fuyukai** [comment]
0.7.8 has been tagged and uploaded to PyPI.

**Comment by brakhane** [comment]
thanks!
